OBJDIR=..\obj
_OBJ=gta.obj directory.obj world.obj pipeline.obj gl.obj\
camera.obj primitives.obj drawable.obj objects.obj
OBJ = $(OBJDIR)\$(_OBJ: = ..\obj\) # can't subsitute $(OBJDIR) here
HEADER = gta.h camera.h directory.h gl.h pipeline.h quat.h world.h \
primitives.h drawable.h objects.h
CC = cl
CFLAGS=/EHsc /DDEBUG
INC = /I..\..\rwtools\src

gtatools: $(OBJ)

{}.cpp{$(OBJDIR)}.obj:
	$(CC) $(CFLAGS) $(INC) /c /Fo$(@) $< 
